# Generated by Django 3.1.6 on 2021-03-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateConsultation', models.DateField(null=True)),
                ('actePoser', models.TextField(blank=True, null=True)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taille', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(blank=True, null=True)),
                ('prenom', models.TextField(blank=True, null=True)),
                ('dateNaissance', models.DateField(null=True)),
                ('specialite', models.TextField(blank=True, null=True)),
                ('secteur', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(blank=True, null=True)),
                ('prenom', models.TextField(blank=True, null=True)),
                ('dateNaissance', models.DateField(null=True)),
                ('assure', models.TextField(blank=True, null=True)),
                ('assurance', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
