# Generated by Django 3.1.6 on 2021-03-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hopital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='diagnostic',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='consultation',
            name='motif',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='profession',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='actePoser',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maladie',
            name='libelle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='prenom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='secteur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assurance',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assure',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prenom',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
